version: '3'
services:
  label-build:
    build:
      context: .
    volumes:
      - ./:/app
  label:
    command: npm start
    ports:
      - "3331:3000"
    build:
      context: ./
    volumes:
      - ./www:/app
      - ./src:/app/src/labellab-components
